<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 12px; }
        .container { border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
        .logo { font-size: 20px; font-weight: 700; color: #1d4ed8; }
        .logo-img { height: 38px; max-width: 180px; object-fit: contain; }
        .title { font-size: 18px; font-weight: 700; margin-top: 6px; }
        .small { color: #6b7280; font-size: 11px; }
        .section { margin-top: 14px; }
        .section h4 { margin: 0 0 6px 0; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: left; }
        th { font-size: 11px; color: #6b7280; text-transform: uppercase; }
        .amount { text-align: right; }
        .total { margin-top: 12px; text-align: right; font-size: 16px; font-weight: 700; }
        .greeting { margin-top: 18px; background: #eff6ff; border: 1px solid #bfdbfe; padding: 10px; border-radius: 8px; }
        .footer { margin-top: 20px; font-size: 10px; color: #6b7280; display: flex; justify-content: space-between; }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('image/dcms-logo.png');
        if (! file_exists($logoPath)) {
            $logoPath = public_path('images/dcms-logo.png');
        }
    @endphp

    <div class="container">
        <div class="header">
            <div>
                @if (file_exists($logoPath))
                    <img src="{{ $logoPath }}" alt="DCMS Logo" class="logo-img">
                @else
                    <div class="logo">DCMS LOGO</div>
                @endif
                <div class="title">Receipt</div>
            </div>
            <div style="text-align: right;">
                <div class="small">Transaction Code</div>
                <div><strong>{{ $history->transaction_code }}</strong></div>
            </div>
        </div>

        <p>Thanks for your purchase.</p>

        <div class="section">
            <h4>Payment Details</h4>
            <div><strong>Date:</strong> {{ optional($paidAt)->format('Y-m-d h:i A') }}</div>
            <div><strong>Account billed:</strong> {{ $history->billed_to_name }} ({{ $history->billed_to_email }})</div>
            <div><strong>Transaction ID:</strong> {{ $displayTransactionId }}</div>
            <div><strong>Charged to:</strong> {{ $history->payment_method_label ?? 'Card payment' }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="amount">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $history->description ?? 'DCMS subscription payment' }}</td>
                    <td class="amount">&#8369; {{ number_format((float) $history->amount, 2) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="total">Total: &#8369; {{ number_format((float) $history->amount, 2) }}</div>

        <div class="greeting">
            We are grateful for your trust in DCMS. Thank you for availing our dental clinic management system. We are committed to supporting your clinic's growth and daily operations.
        </div>

        <div class="footer">
            <span>Digital Transaction: {{ $signature }}</span>
            <span>Generated by DCMS</span>
        </div>
    </div>
</body>
</html>
